  roll-kdf-version:
    needs: check-for-updates
    if: ${{ needs.check-for-updates.outputs.has_updates == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Dart SDK
        uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: |
          cd packages/komodo_wallet_cli
          dart pub get

      - name: Create branch for roll
        run: |
          BRANCH="${{ needs.check-for-updates.outputs.branch }}"
          NEW_COMMIT="${{ needs.check-for-updates.outputs.new_commit }}"
          SHORT_COMMIT="${NEW_COMMIT:0:7}"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git checkout -b kdf-roll/$BRANCH-$SHORT_COMMIT

      - name: Roll KDF version
        id: roll-version
        run: |
          BRANCH="${{ needs.check-for-updates.outputs.branch }}"
          CURRENT_COMMIT="${{ needs.check-for-updates.outputs.current_commit }}"
          NEW_COMMIT="${{ needs.check-for-updates.outputs.new_commit }}"
          SOURCE_URLS='${{ needs.check-for-updates.outputs.source_urls }}'
          echo "Running update_api_config tool..."
          cd packages/komodo_wallet_cli
          mkdir -p ../komodo_defi_framework/app_build/temp_downloads
          SUCCESS=false
          for SOURCE_URL in $(echo $SOURCE_URLS | jq -r '.[]'); do
            echo "Trying source URL: $SOURCE_URL"
            if [[ "$SOURCE_URL" == *"api.github.com"* ]]; then
              SOURCE_TYPE="github"
            else
              SOURCE_TYPE="mirror"
            fi
            echo "Using source type: $SOURCE_TYPE"
            if dart bin/update_api_config.dart \
              --branch "$BRANCH" \
              --source "$SOURCE_TYPE" \
              --config ../komodo_defi_framework/app_build/build_config.json \
              --output-dir ../komodo_defi_framework/app_build/temp_downloads \
              --verbose; then
              echo "Successfully rolled using $SOURCE_URL"
              SUCCESS=true
              break
            else
              echo "Failed to roll using $SOURCE_URL, trying next source..."
            fi
          done
          if [ "$SUCCESS" = false ]; then
            echo "All sources failed. Exiting with error."
            exit 1
          fi

      - name: Commit and push changes
        env:
          TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          BRANCH="${{ needs.check-for-updates.outputs.branch }}"
          NEW_COMMIT="${{ needs.check-for-updates.outputs.new_commit }}"
          SHORT_COMMIT="${NEW_COMMIT:0:7}"

          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git add packages/komodo_defi_framework/app_build/build_config.json
          git commit -m "chore: roll KDF version to commit $SHORT_COMMIT for branch $BRANCH"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
          git push origin kdf-roll/$BRANCH-$SHORT_COMMIT

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          BRANCH="${{ needs.check-for-updates.outputs.branch }}"
          NEW_COMMIT="${{ needs.check-for-updates.outputs.new_commit }}"
          SHORT_COMMIT="${NEW_COMMIT:0:7}"
          PR_TITLE="chore: roll KDF version to commit $SHORT_COMMIT for branch $BRANCH"
          PR_BODY="This PR rolls the KDF version to the latest commit ($SHORT_COMMIT) for the '$BRANCH' branch.

**Changes:**
- Rolled KDF version from \`${{ needs.check-for-updates.outputs.current_commit }}\` to \`$NEW_COMMIT\`

This PR was automatically generated by GitHub Actions."

          echo "$GH_TOKEN" | gh auth login --with-token
          gh pr create \
            --title "$PR_TITLE" \
            --body "$PR_BODY" \
            --base "$BRANCH" \
            --head "kdf-roll/$BRANCH-$SHORT_COMMIT"
