name: Roll KDF Version

on:
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight UTC
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to check for rolls (dev or main)"
        required: false
        default: ""
        type: string

jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    outputs:
      has_updates: ${{ steps.check-updates.outputs.has_updates }}
      branch: ${{ steps.determine-branch.outputs.branch }}
      current_commit: ${{ steps.current-details.outputs.commit }}
      new_commit: ${{ steps.check-updates.outputs.new_commit }}
      source_urls: ${{ steps.get-source-urls.outputs.source_urls }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      # [Previous steps remain the same...]

  roll-kdf-version:
    needs: check-for-updates
    if: ${{ needs.check-for-updates.outputs.has_updates == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Dart SDK
        uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: |
          cd packages/komodo_wallet_cli
          dart pub get

      - name: Create branch for roll
        run: |
          BRANCH="${{ needs.check-for-updates.outputs.branch }}"
          NEW_COMMIT="${{ needs.check-for-updates.outputs.new_commit }}"
          SHORT_COMMIT="${NEW_COMMIT:0:7}"
          
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git fetch origin
          git checkout -b kdf-roll/$BRANCH-$SHORT_COMMIT

      # [Roll version steps remain the same...]

      - name: Commit and push changes
        run: |
          BRANCH="${{ needs.check-for-updates.outputs.branch }}"
          NEW_COMMIT="${{ needs.check-for-updates.outputs.new_commit }}"
          SHORT_COMMIT="${NEW_COMMIT:0:7}"
          
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          git add packages/komodo_defi_framework/app_build/build_config.json
          git commit -m "chore: roll KDF version to commit $SHORT_COMMIT for branch $BRANCH"
          git push origin kdf-roll/$BRANCH-$SHORT_COMMIT

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH="${{ needs.check-for-updates.outputs.branch }}"
          NEW_COMMIT="${{ needs.check-for-updates.outputs.new_commit }}"
          SHORT_COMMIT="${NEW_COMMIT:0:7}"
          
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/pulls \
            -f title="chore: roll KDF version to $SHORT_COMMIT ($BRANCH)" \
            -f body="Automated version update to commit $NEW_COMMIT" \
            -f head="kdf-roll/$BRANCH-$SHORT_COMMIT" \
            -f base="$BRANCH"
